[project]
name = "source-exact"
version = "0.2.0"
description = "Connector for the bookkeeping software exact online"
authors = [
    { name = "Jeroen de Vries", email = "jeroen@maildevries.eu" }
]
license = { text = "MIT" }
readme = "README.md"
requires-python = ">=3.11,<3.13"
dependencies = [
    "airbyte-cdk (>=6.48.16,<7.0.0)",
    "pendulum (>=3.1.0,<4.0.0)"
]



[dependency-groups]
dev = [
    "pytest>=8.4.0",
    "pytest-mock>=3.14.1",
    "ruff>=0.11.12",
    "source-acceptance-test>=1.0.0",
]

