[tool.poetry]
name = "source-exact"
version = "0.2.0"
description = "Source connector for Exact Online"
authors = ["Jeroen de Vries <jeroen@maildevries.eu>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.11,<3.12"
google-cloud-secret-manager = "^2.24.0"
airbyte-cdk = "^6.55.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[project.scripts]
source-exact = "source_exact.run:run"